### PR TITLE
Add travis

### PR DESCRIPTION
**Pull request by anderspitman**
In it's current state this adds a barebones travis run that will download the primary dependencies and run sisrs --version just to verify that it works. Once we have some sample data we can start making real tests.

### CODE REVIEW

**Comment by anderspitman** [comment]
@rachelss once we get this merged you'll need to create a Travis account if you don't already have one and enable testing for this repo. It's very easy to do; literally flipping a switch.

**Comment by anderspitman** [comment]
@rachelss did you get a chance to look at this?

**Comment by rachelss** [comment]
Missed it. Sorry. Thanks for the reminder. I enabled Travis for SISRS.

**Comment by anderspitman** [comment]
Thanks!

**Pull request merged**
