### PR TITLE
RAL Python

### PR DESCRIPTION
**Pull request by BobLiterman**
This version of SISRS works from top to bottom with the test data and uses the newer streaming file handling protocols.

### CODE REVIEW

**Comment by rachelss** [comment]
@anderspitman why does Travis fail and can we fix it?

**Comment by BobLiterman** [comment]
@anderspitman may know?

**Comment by anderspitman** [comment]
You can click on the `Details` link to see the output from the run. As discussed in #36, the tests (tests/test_sisrs.py) and test data are going to have to be updated to match the changes made by @BobLiterman. It's best to keep that in sync as you go along, making sure the tests still pass before each commit. If you haven't been doing that it might be pretty painful to figure out why it's failing. Also you'll need to be very careful when making changes to tests and test data because if you've introduced any bugs regenerating the test data is dangerous.

**Comment by anderspitman** [comment]
Basically the passing test suite is our single source of truth. Anything committed to the repo needs to conform to it. It's ok for the test suite to be updated, but that process has to be done carefully and heavily audited, like amending the constitution.

**Pull request merged**
